displayName=2005Scape
author=tkoh-v7
description=Personal historical challenge with a 22 June 2005 cutoff
tags=2005,classic,ironman,restrictions
plugins=com.tkoh.scape2005.Scape2005Plugin
version=0.5.0
build=standard
